branches:
  only:
    - master

before_install:
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:libreoffice/libreoffice-6-3
  - sudo apt-get update -q
  - sudo apt-get install -y -qq lcov curl doxygen graphviz

script:
  - doxygen Doxyfile
  - make
  - make run_import
  - ls -la *
  - make run_display

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master