branches:
  only:
    - master

before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update
  - sudo apt-get install doxygen

script:
  - doxygen Doxyfile
  - make
  - make run_import
  - ls -la *
  - make run_display

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master