branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - make
  - make run_import
  - ls -la *
  - make run_display
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master