os: linux
dist: trusty
language: cpp

sudo: enabled

before_install:

  - export DOXYGEN_VER=doxygen-1.8.16
  - export DOXYGEN_TAR=${DOXYGEN_VER}.linux.bin.tar.gz
  - export DOXYGEN_URL="http://doxygen.nl/files/${DOXYGEN_TAR}"

before_script:
  - sudo pip install ghp-import
  - wget -O - "${DOXYGEN_URL}" | tar xz -C ${TMPDIR-/tmp} ${DOXYGEN_VER}/bin/doxygen
  - export PATH="${TMPDIR-/tmp}/${DOXYGEN_VER}/bin:$PATH"



branches:
  only:
    - master


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - texlive
      - texlive-latex-extra
      - libclang


script:
  - doxygen Doxyfile
  - cd docs/latex && make
  - cd ../../
  - mv docs/latex/refman.pdf docs/html/Documentation.pdf
  - rm -r docs/latex
  - make
  - make run_import
  - ls -la *
  - make run_display

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master