language: cpp

sudo: enabled

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen texlive texlive-latex-extra

script:
  - doxygen Doxyfile
  - cd docs/latex && make
  - cd ../../
  - mv docs/latex/refman.pdf docs/html/Documentation.pdf
  - rm -r docs/latex
  - make
  - make run_import
  - ls -la *
  - make run_display

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master